spring:
  application.name: experiment
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    open-in-view: false
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
